language: node_js

node_js:
  - 12.18.3

cache: yarn

env:
  - CI=true

before_install:
  - cd frontend

before_deploy:
  - yarn global add netlify-cli
  - yarn run build

script:
  - yarn test

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_PUBLISH_KEY -p ./build
  skip_cleanup: true
  on:
    branch: feature/FrontEnd/editButton
